# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160606161117 on 2016-07-05 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_word', models.IntegerField()),
                ('term', models.CharField(max_length=30)),
                ('definition', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
