# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('alphabet', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language'),
        ),
    ]
