# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20160708_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(max_length=150),
        ),
    ]
