# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20160713_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='stage',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
